### ISSUE TITLE
Nullpointer exception in onLocationChanged in SelectTransit

### ISSUE THREAD

**Issue by epicstar** [rectangle-dbmi/Realtime-Port-Authority#190]
```
java.lang.NullPointerException
at rectangledbmi.com.pittsburghrealtimetracker.SelectTransit.onLocationChanged(SelectTransit.java:956)
at com.google.android.gms.location.internal.zzi$zzb.handleMessage(Unknown Source)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:153)
at android.app.ActivityThread.main(ActivityThread.java:5313)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:511)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:833)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
at dalvik.system.NativeStart.main(Native Method)
```

**Comment by epicstar** [comment]
Found the offending piece of code and it's a pretty bad oversight on my part....

https://github.com/rectangle-dbmi/Realtime-Port-Authority/blob/master/Android/Pittsburgh_Realtime_Tracker/app/src/main/java/rectangledbmi/com/pittsburghrealtimetracker/SelectTransit.java#L956
